### ISSUE TITLE
Read the M0 document carefully for what it is that you have to return at this route.

### ISSUE THREAD

**Issue by chrzrdx** [suryakumarigoluguri/edyst-s19-choose-a-pokemon#1]
https://github.com/suryakumarigoluguri/edyst-s19-choose-a-pokemon/blob/cdcf4ebcc24250580e6d4e5809d1d37ec546b251/app.py#L7

**Comment by suryakumarigoluguri** [comment]
sorry sir,i did not seen it clearly
