### ISSUE TITLE
frontend: issues

### ISSUE THREAD

**Issue by chrzrdx** [suryakumarigoluguri/edyst-s19-choose-a-pokemon#7]
![surya](https://user-images.githubusercontent.com/17521606/57162444-ea882f80-6e0b-11e9-92d2-264faffee6b7.png)

When the window is resized slightly, the boxes don't contain the cards anymore.

Look at how you can layout these cards/elements better so they can respond to the window width changes

**Comment by suryakumarigoluguri** [comment]
Thank you,for letting me know this issue.
I have resolved that one,
You can check it now.
